# Generated by Django 3.2.25 on 2024-11-18 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AuthenticationCenter', '0004_user_is_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('cID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('academic_year', models.CharField(max_length=40)),
                ('mCode', models.CharField(max_length=20)),
                ('credits', models.IntegerField()),
                ('level', models.IntegerField()),
                ('semester', models.CharField(max_length=40)),
                ('summary', models.TextField()),
                ('aims', models.TextField()),
                ('method_frequency', models.TextField()),
                ('assessment', models.TextField()),
                ('assessment_period', models.TextField()),
                ('outcomes', models.TextField()),
                ('dID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AuthenticationCenter.department')),
                ('wID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AuthenticationCenter.teacher')),
            ],
        ),
    ]
