# Generated by Django 3.2.25 on 2024-11-30 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AuthenticationCenter', '0004_user_is_staff'),
        ('CourseCenter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stars',
            fields=[
                ('rID', models.AutoField(primary_key=True, serialize=False)),
                ('cID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CourseCenter.course')),
                ('sID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AuthenticationCenter.student')),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('rID', models.AutoField(primary_key=True, serialize=False)),
                ('cID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CourseCenter.course')),
                ('sID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AuthenticationCenter.student')),
            ],
        ),
    ]
