# Generated by Django 3.2.25 on 2024-12-02 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AuthenticationCenter', '0004_user_is_staff'),
        ('CourseCenter', '0002_enrollment_stars'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stars',
            new_name='Star',
        ),
        migrations.RenameField(
            model_name='enrollment',
            old_name='rID',
            new_name='eID',
        ),
    ]
