# Generated by Django 3.2.25 on 2024-11-12 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('dID', models.AutoField(primary_key=True, serialize=False)),
                ('School', models.CharField(max_length=255)),
                ('Campus', models.CharField(blank=True, max_length=40)),
                ('Faculty', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('is_user', models.BooleanField(default=True)),
                ('is_teacher', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='AuthenticationCenter.user')),
                ('wID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
                ('Title', models.CharField(max_length=40)),
                ('Telephone', models.CharField(blank=True, max_length=20)),
                ('dID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AuthenticationCenter.department')),
            ],
            options={
                'abstract': False,
            },
            bases=('AuthenticationCenter.user',),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='AuthenticationCenter.user')),
                ('sID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=1)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('dID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AuthenticationCenter.department')),
            ],
            options={
                'abstract': False,
            },
            bases=('AuthenticationCenter.user',),
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='AuthenticationCenter.user')),
                ('aID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
                ('dID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AuthenticationCenter.department')),
            ],
            options={
                'abstract': False,
            },
            bases=('AuthenticationCenter.user',),
        ),
    ]
