# Generated by Django 3.2.25 on 2024-11-14 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AuthenticationCenter', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin',
            old_name='Name',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='Name',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='Name',
            new_name='username',
        ),
    ]
