# Generated by Django 3.2.25 on 2024-11-16 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthenticationCenter', '0002_auto_20241114_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='Title',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
