# Generated by Django 3.2.25 on 2024-11-17 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthenticationCenter', '0003_auto_20241116_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
